### ISSUE TITLE
usage as regular AxiosInstance

### ISSUE THREAD

**Issue by landsman** [divyam234/feaxios#1]
I discovered your package and I tried to use it as `AxiosInstance`.
My goal is to use fetch on server (because of Next.js) and Axios on frontend side where this would be nice way how to mantain current code, api interfaces of axios.

```node
TS2739: Type AxiosInstance is missing the following properties from type AxiosInstance: getUri, postForm, putForm, patchForm
```

**Comment by divyam234** [comment]
@landsman  it can be added I will add it in next release.
